version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - mongodb
      - redis
      - chroma
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - smart-reader-network

  # Chat UI
  chat-ui:
    build: ./services/chat-ui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./services/chat-ui:/app
      - /app/node_modules
    networks:
      - smart-reader-network

  # Document Processing Service
  document-processing:
    build: ./services/document-processing
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/smart-reader
    depends_on:
      - mongodb
    volumes:
      - ./services/document-processing:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - smart-reader-network

  # AI Integration Service
  ai-integration:
    build: ./services/ai-integration
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MONGODB_URI=mongodb://mongodb:27017/smart-reader
    depends_on:
      - mongodb
    volumes:
      - ./services/ai-integration:/app
      - /app/node_modules
    networks:
      - smart-reader-network

  # Vector Database Service
  vector-database:
    build: ./services/vector-database
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017/smart-reader
    depends_on:
      - mongodb
      - chroma
    volumes:
      - ./services/vector-database:/app
      - /app/node_modules
    networks:
      - smart-reader-network

  # Chat API Service
  chat-api:
    build: ./services/chat-api
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGODB_URI=mongodb://mongodb:27017/smart-reader
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./services/chat-api:/app
      - /app/node_modules
    networks:
      - smart-reader-network

  # File Storage Service
  file-storage:
    build: ./services/file-storage
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - MONGODB_URI=mongodb://mongodb:27017/smart-reader
    depends_on:
      - mongodb
    volumes:
      - ./services/file-storage:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - smart-reader-network

  # MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=smart-reader
    volumes:
      - mongodb_data:/data/db
    networks:
      - smart-reader-network

  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-reader-network

  # ChromaDB
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - smart-reader-network

volumes:
  mongodb_data:
  redis_data:
  chroma_data:

networks:
  smart-reader-network:
    driver: bridge